# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mt_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_mt_name', models.CharField(default='mt', max_length=100)),
                ('f_access_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['f_mt_name'],
            },
        ),
        migrations.CreateModel(
            name='mt_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_product_id', models.IntegerField(default=0, unique=True)),
                ('f_product_name', models.CharField(default='prodname', max_length=100)),
                ('f_quantity_unit', models.CharField(default='unit', max_length=100)),
                ('f_creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('f_product_category', models.CharField(default='category', max_length=100)),
                ('f_product_description', models.CharField(default='description', max_length=1000)),
                ('f_product_images_link', models.CharField(default='images', max_length=1000)),
                ('f_product_video_link', models.CharField(default='video', max_length=1000)),
                ('f_product_dimension_units', models.CharField(default='category', max_length=100)),
                ('f_product_dimension_height', models.IntegerField(default=0)),
                ('f_product_dimension_width', models.IntegerField(default=0)),
                ('f_product_dimension_depth', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['f_product_id'],
            },
        ),
        migrations.CreateModel(
            name='mt_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_service_id', models.IntegerField(default=0, unique=True)),
                ('f_service_name', models.CharField(default='servname', max_length=100)),
                ('f_duration_unit', models.CharField(default='unit', max_length=100)),
                ('f_creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('f_service_category', models.CharField(default='category', max_length=100)),
                ('f_service_description', models.CharField(default='description', max_length=1000)),
            ],
            options={
                'ordering': ['f_service_id'],
            },
        ),
        migrations.CreateModel(
            name='mt_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_trans_id', models.IntegerField(default=0, unique=True)),
                ('f_user_id1', models.IntegerField(default=0)),
                ('f_user_id2', models.IntegerField(default=0)),
                ('f_status', models.CharField(default='c', max_length=1)),
                ('f_creation_time_a', models.DateTimeField(default=datetime.datetime.now)),
                ('f_creation_time_b', models.DateTimeField(default=datetime.datetime.now)),
                ('f_approval_time_h', models.DateTimeField(default=datetime.datetime.now)),
                ('f_approval_time_x', models.DateTimeField(default=datetime.datetime.now)),
                ('f_ft_type', models.CharField(default='x', max_length=1)),
                ('f_ft_id', models.IntegerField(default=0)),
                ('f_ft_quantity_unit', models.CharField(default='xx', max_length=2)),
                ('f_ft_quantity_number', models.IntegerField(default=0)),
                ('f_ft_category', models.CharField(default='category', max_length=100)),
                ('f_ft_description', models.CharField(default='description', max_length=1000)),
                ('f_pt_type', models.CharField(default='x', max_length=1)),
                ('f_pt_id', models.IntegerField(default=0)),
                ('f_pt_quantity_unit', models.CharField(default='xx', max_length=2)),
                ('f_pt_quantity_number', models.IntegerField(default=0)),
                ('f_pt_category', models.CharField(default='category', max_length=100)),
                ('f_pt_description', models.CharField(default='description', max_length=1000)),
                ('f_hash_pk', models.CharField(default='pk', max_length=1000)),
                ('f_hash_u1', models.CharField(default='u1', max_length=1000)),
                ('f_hash_u2', models.CharField(default='u2', max_length=1000)),
            ],
            options={
                'ordering': ['f_trans_id'],
            },
        ),
        migrations.CreateModel(
            name='mt_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_user_id', models.IntegerField(default=0, unique=True)),
                ('f_user_name', models.CharField(default='username', max_length=100)),
                ('f_verification_status', models.BooleanField(default=False)),
                ('f_creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('f_verification_time', models.DateTimeField(default=datetime.datetime.now)),
                ('f_id_type', models.CharField(default='idt', max_length=100)),
                ('f_id_number', models.CharField(default='idn', max_length=1000)),
                ('f_nationality', models.CharField(default='country', max_length=100)),
                ('f_email_id', models.CharField(default='email', max_length=1000, unique=True)),
                ('f_contact_number', models.CharField(default='contact', max_length=100)),
            ],
            options={
                'ordering': ['f_user_id'],
            },
        ),
    ]
