# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sc', '0002_auto_20171122_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt_users',
            name='f_user_name',
            field=models.CharField(default='username', max_length=100, unique=True),
        ),
    ]
