# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sc', '0003_auto_20171123_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt_transactions',
            name='f_ft_quantity_unit',
            field=models.CharField(choices=[('sc', 'Seconds'), ('mn', 'Minutes'), ('hr', 'Hours'), ('un', 'Units'), ('kg', 'Kilograms'), ('cm', 'Cubic Meter'), ('rp', 'Rupee'), ('dl', 'Dollar'), ('eu', 'Euro')], default='xx', max_length=2),
        ),
        migrations.AlterField(
            model_name='mt_transactions',
            name='f_pt_quantity_unit',
            field=models.CharField(choices=[('sc', 'Seconds'), ('mn', 'Minutes'), ('hr', 'Hours'), ('un', 'Units'), ('kg', 'Kilograms'), ('cm', 'Cubic Meter'), ('rp', 'Rupee'), ('dl', 'Dollar'), ('eu', 'Euro')], default='xx', max_length=2),
        ),
    ]
