# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sc', '0004_auto_20171123_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt_transactions',
            name='f_ft_type',
            field=models.CharField(choices=[('m', 'Money'), ('p', 'Product'), ('s', 'Service')], default='x', max_length=1),
        ),
        migrations.AlterField(
            model_name='mt_transactions',
            name='f_pt_type',
            field=models.CharField(choices=[('m', 'Money'), ('p', 'Product'), ('s', 'Service')], default='x', max_length=1),
        ),
    ]
