# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sc', '0005_auto_20171123_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt_transactions',
            name='f_creator',
            field=models.IntegerField(default=0),
        ),
    ]
