# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sc', '0006_mt_transactions_f_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt_transactions',
            name='f_first_half_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
