# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sc', '0007_mt_transactions_f_first_half_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mt_cred_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='name', max_length=100)),
                ('f_email', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['f_name'],
            },
        ),
    ]
